import 'package:cloud_firestore/cloud_firestore.dart';
import '../models/audit_log_model.dart';

/// Service for managing audit logs
class AuditLogService {
  final FirebaseFirestore _firestore;
  
  AuditLogService({FirebaseFirestore? firestore})
      : _firestore = firestore ?? FirebaseFirestore.instance;

  /// Log an audit entry
  Future<void> logActivity({
    required String userId,
    required String userRole,
    required String operation,
    required String module,
    required String subModule,
    required String targetEntity,
    String? targetId,
    List<String>? affectedUsers,
    Map<String, dynamic>? details,
    Map<String, dynamic>? metadata,
  }) async {
    try {
      print('🔍 Logging audit entry: $module - $operation by $userId');
      
      final logEntry = AuditLogEntry(
        logId: '', // Will be auto-generated by Firestore
        timestamp: DateTime.now(),
        userId: userId,
        userRole: userRole,
        operation: operation,
        module: module,
        subModule: subModule,
        targetEntity: targetEntity,
        targetId: targetId,
        affectedUsers: affectedUsers ?? [],
        details: details ?? {},
        metadata: metadata,
      );

      await _firestore.collection('auditLogs').add(logEntry.toFirestore());
      print('✅ Audit log saved successfully');
    } catch (e) {
      // Log to console but don't throw to avoid breaking main operations
      print('❌ Failed to log audit entry: $e');
      print('Stack trace: ${StackTrace.current}');
    }
  }

  /// Log faculty marks posting
  Future<void> logMarksPosting({
    required String facultyId,
    required String marksType, // 'cie', 'supply', 'makeup'
    required String courseCode,
    required String section,
    required List<String> studentRollNos,
    Map<String, dynamic>? additionalDetails,
  }) async {
    await logActivity(
      userId: facultyId,
      userRole: 'faculty',
      operation: 'create',
      module: 'marks',
      subModule: '${marksType}_marks',
      targetEntity: 'studentMarks',
      affectedUsers: studentRollNos,
      details: {
        'courseCode': courseCode,
        'section': section,
        'marksType': marksType,
        'studentCount': studentRollNos.length,
        ...?additionalDetails,
      },
    );
  }

  /// Log fee payment status update
  Future<void> logFeePayment({
    required String staffId,
    required String paymentType, // 'supply', 'makeup_mid'
    required String windowId,
    required String studentRollNo,
    required String status, // 'paid', 'unpaid'
    required double amount,
    Map<String, dynamic>? additionalDetails,
  }) async {
    await logActivity(
      userId: staffId,
      userRole: 'fee_payment',
      operation: 'update',
      module: 'fees',
      subModule: '${paymentType}_fees',
      targetEntity: 'feePayments',
      targetId: '${paymentType}_${windowId}_$studentRollNo',
      affectedUsers: [studentRollNo],
      details: {
        'windowId': windowId,
        'status': status,
        'amount': amount,
        'paymentType': paymentType,
        ...?additionalDetails,
      },
    );
  }

  /// Log faculty profile update
  Future<void> logFacultyProfileUpdate({
    required String facultyId,
    required Map<String, dynamic> updatedFields,
    Map<String, dynamic>? oldValues,
  }) async {
    await logActivity(
      userId: facultyId,
      userRole: 'faculty',
      operation: 'update',
      module: 'profile',
      subModule: 'faculty_profile',
      targetEntity: 'faculty',
      targetId: facultyId,
      affectedUsers: [facultyId],
      details: {
        'updatedFields': updatedFields.keys.toList(),
        'oldValues': oldValues,
        'newValues': updatedFields,
      },
    );
  }

  /// Log student grievance submission
  Future<void> logGrievanceSubmission({
    required String studentRollNo,
    required String grievanceId,
    required String grievanceType,
    required String subject,
  }) async {
    await logActivity(
      userId: studentRollNo,
      userRole: 'student',
      operation: 'create',
      module: 'grievance',
      subModule: 'grievance',
      targetEntity: 'grievances',
      targetId: grievanceId,
      affectedUsers: [studentRollNo],
      details: {
        'grievanceType': grievanceType,
        'subject': subject,
      },
    );
  }

  /// Log student feedback submission
  Future<void> logFeedbackSubmission({
    required String studentRollNo,
    required String sessionId,
    required String facultyId,
    String? courseCode,
  }) async {
    await logActivity(
      userId: studentRollNo,
      userRole: 'student',
      operation: 'submit',
      module: 'feedback',
      subModule: 'feedback',
      targetEntity: 'feedback',
      targetId: sessionId,
      affectedUsers: [studentRollNo],
      details: {
        'sessionId': sessionId,
        'facultyId': facultyId,
        'courseCode': courseCode,
      },
    );
  }

  /// Get audit logs with filters
  /// Note: To avoid requiring complex Firestore indexes, we filter in-memory
  /// for multiple conditions. Only single where clause is applied to Firestore.
  Stream<List<AuditLogEntry>> getAuditLogs({
    String? userId,
    String? userRole,
    String? module,
    String? subModule,
    DateTime? startDate,
    DateTime? endDate,
    int limit = 100,
  }) {
    print('🔍 Fetching audit logs with limit: $limit');
    
    Query query = _firestore.collection('auditLogs');
    bool usedWhereClause = false;

    // Apply only ONE where clause to avoid composite index requirements
    // Priority: userId > userRole > module > date range (startDate only)
    if (userId != null && userId.isNotEmpty) {
      query = query.where('userId', isEqualTo: userId);
      usedWhereClause = true;
    } else if (userRole != null) {
      query = query.where('userRole', isEqualTo: userRole);
      usedWhereClause = true;
    } else if (module != null) {
      query = query.where('module', isEqualTo: module);
      usedWhereClause = true;
    } else if (startDate != null) {
      query = query.where('timestamp', isGreaterThanOrEqualTo: startDate);
      usedWhereClause = true;
      // Note: endDate filter will be applied in-memory to avoid composite index
    }

    // Only orderBy timestamp if we didn't use a where clause on other fields
    if (usedWhereClause && (userId != null || userRole != null || module != null)) {
      // Cannot use orderBy with where on different field
      query = query.limit(limit * 2);
    } else {
      query = query.orderBy('timestamp', descending: true).limit(limit * 2);
    }

    return query.snapshots().map((snapshot) {
      print('📦 Received ${snapshot.docs.length} audit log documents from Firestore');
      
      var logs = snapshot.docs
          .map((doc) => AuditLogEntry.fromFirestore(doc))
          .toList();

      // Sort by timestamp if we couldn't do it in Firestore
      if (usedWhereClause && (userId != null || userRole != null || module != null)) {
        logs.sort((a, b) => b.timestamp.compareTo(a.timestamp));
      }

      // Apply additional filters in-memory
      if (userId != null && userId.isNotEmpty) {
        logs = logs.where((log) => log.userId == userId).toList();
      }
      if (userRole != null) {
        logs = logs.where((log) => log.userRole == userRole).toList();
      }
      if (module != null) {
        logs = logs.where((log) => log.module == module).toList();
      }
      if (subModule != null) {
        logs = logs.where((log) => log.subModule == subModule).toList();
      }
      if (startDate != null) {
        logs = logs.where((log) => !log.timestamp.isBefore(startDate)).toList();
      }
      if (endDate != null) {
        logs = logs
            .where((log) => log.timestamp.isBefore(endDate.add(const Duration(days: 1))))
            .toList();
      }

      // Limit results
      if (logs.length > limit) {
        logs = logs.sublist(0, limit);
      }

      print('✅ Returning ${logs.length} filtered audit logs');
      return logs;
    });
  }

  /// Get audit log statistics
  /// Fetches all logs and computes stats in-memory to avoid index requirements
  Future<Map<String, int>> getLogStatistics({
    DateTime? startDate,
    DateTime? endDate,
  }) async {
    Query query = _firestore.collection('auditLogs');

    // Only apply startDate filter to Firestore, endDate will be filtered in-memory
    if (startDate != null) {
      query = query.where('timestamp', isGreaterThanOrEqualTo: startDate);
    }
    
    // Limit to recent logs for performance
    query = query.orderBy('timestamp', descending: true).limit(500);

    final snapshot = await query.get();
    
    final stats = <String, int>{
      'total': 0,
      'marks': 0,
      'fees': 0,
      'grievance': 0,
      'feedback': 0,
      'profile': 0,
    };

    for (final doc in snapshot.docs) {
      final data = doc.data() as Map<String, dynamic>;
      final timestamp = (data['timestamp'] as Timestamp?)?.toDate();
      
      // Apply date filters in-memory
      if (startDate != null && timestamp != null && timestamp.isBefore(startDate)) {
        continue;
      }
      if (endDate != null && timestamp != null && timestamp.isAfter(endDate.add(const Duration(days: 1)))) {
        continue;
      }
      
      stats['total'] = (stats['total'] ?? 0) + 1;
      
      final module = data['module'] as String?;
      if (module != null && stats.containsKey(module)) {
        stats[module] = (stats[module] ?? 0) + 1;
      }
    }

    return stats;
  }

  /// Delete all audit logs (called during student promotion)
  Future<void> deleteAllAuditLogs() async {
    try {
      print('🗑️ Starting to delete all audit logs...');
      
      // Fetch all audit logs in batches and delete
      const batchSize = 500;
      bool hasMore = true;
      int totalDeleted = 0;
      
      while (hasMore) {
        final snapshot = await _firestore
            .collection('auditLogs')
            .limit(batchSize)
            .get();
        
        if (snapshot.docs.isEmpty) {
          hasMore = false;
          break;
        }
        
        // Delete in batches of 500 (Firestore batch limit)
        final batch = _firestore.batch();
        for (final doc in snapshot.docs) {
          batch.delete(doc.reference);
        }
        await batch.commit();
        
        totalDeleted += snapshot.docs.length;
        print('🗑️ Deleted $totalDeleted audit logs so far...');
        
        // If we got fewer docs than batch size, we're done
        if (snapshot.docs.length < batchSize) {
          hasMore = false;
        }
      }
      
      print('✅ Successfully deleted $totalDeleted audit logs');
    } catch (e) {
      print('❌ Failed to delete audit logs: $e');
      throw Exception('Failed to delete audit logs: $e');
    }
  }
}
